### ISSUE TITLE
Split up and explain the various usage examples

### ISSUE THREAD

**Issue by humphd** [a-rokay/static-site-generator#4]
There are a number of [Usage](https://github.com/a-rokay/static-site-generator#usage) examples given, but no explanation for any of them or what they do.  Later you list the help output, but it would be good to give some explanation of how each of the different args/flags work, when to use them, how to combine them, etc.

**Comment by a-rokay** [comment]
I've expanded on both of those sections. Thanks!

**Comment by humphd** [comment]
Looks good.
